image: ubuntu

services:
- docker

build: off

test_script:
  - sh: docker run -v /home/appveyor/projects/project-euler/src/r/:/toBeTested -t fazenda/r-testing /bin/sh -c "cd toBeTested && R -e 'devtools::test()'"
