image: ubuntu

services:
- docker

build: off

before_test:
  - sh: cd src
  - sh: cd r

test_script:
  - sh: |
        docker run -t fazenda/r-testing -eo pipefail
        cd ./src/r/
        R -e 'devtools::test()'
