/*
                            Even Fibonacci numbers

	Each  new term in the Fibonacci sequence is generated by adding the previous
	two terms. By starting with 1 and 2, the first 10 terms will be:

					1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By  considering  the  terms  in  the  Fibonacci sequence whose values do not
	exceed four million, find the sum of the even-valued terms.

								Answer: 4613732
*/

#include <stdio.h>
#include "../lib/data/data.h"
#include "../lib/list/int/listint.h"
#include "../lib/project_euler/project_euler.h"

static ListInt * fibonacciUntil (unsigned long int limit) {
    ListInt * list = allocListInt();
    long int value = 3;
    Index nth = 4;

    if (isNotNull (list)) {
        pushListInt (list, 1);
        pushListInt (list, 2);

        while (value < limit) {
            pushListInt (list, value);
            value = postionListInt (list, nth - 1) + postionListInt (list, nth - 2);
            nth += 1;
        }
    }

    return list;
}

static ListInt * evenFibonacciUntil (unsigned long int limit) {
    ListInt * fib = fibonacciUntil (limit), * even = NULL;

    if (isNotNull (fib)) {
        even = filterListInt (fib, isIntEven);
        freeListInt (&fib);
    }

    return even;
}

int main (int argc, char ** argv) {
    long int limit = 4000000, result = 0;
    ListInt * even = evenFibonacciUntil (limit);

    if (isNotNull (even)) {
        result = reduceListInt (even, sumInt, result);
        freeListInt (&even);
    }

    printf ("%ld\n", result);

    return 0;
}
