=begin
					Triangular, pentagonal, and hexagonal

	Triangle,  pentagonal,  and hexagonal numbers are generated by the following
	formulae:

	Triangle	 	Tn=n(n+1)/2	 		1, 3, 6, 10, 15, ...
	Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
	Hexagonal	 	Hn=n(2n−1)	 		1, 6, 15, 28, 45, ...
	
	It can be verified that T285 = P165 = H143 = 40755.

	Find the next triangle number that is also pentagonal and hexagonal.
=end

def is_pentagonal( pn )
	return 0 == ( ( Math.sqrt( 1 + 24*pn ) + 1.0 ) / 6.0 ) % 1
end

def is_hexagonal( hn )
	return 0 == ( ( Math.sqrt( 1 + 8*hn ) + 1.0 ) / 4.0 ) % 1
end

def triangular_pentagonal_hexagonal( limit )
	matches = []
	n = 1

	while matches.length < limit do
		n += 1
		triangle = n*( n+1 ) / 2
		matches.push( triangle ) if is_pentagonal( triangle ) && 
									is_hexagonal( triangle )
	end

	return matches
end

pos = 2
puts triangular_pentagonal_hexagonal( pos )[ pos - 1 ]