#=
							Even Fibonacci numbers

	Each  new term in the Fibonacci sequence is generated by adding the previous
	two terms. By starting with 1 and 2, the first 10 terms will be:

					1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By  considering  the  terms  in  the  Fibonacci sequence whose values do not
	exceed four million, find the sum of the even-valued terms.

								Answer: 4613732
=#

function fibonacci(limit::Int)
    array = [1, 2]
    flag = true
    i = 2

    while flag
        new_value = array[i]+array[i-1]

        if new_value < limit
            push!(array, new_value)
            i += 1
        else
            flag = false
        end
    end

    return array
end

println(sum(filter(iseven, fibonacci(4_000_000))))
