"""
                        Highly divisible triangular number

    The sequence of triangle numbers is generated by adding the natural numbers.
    So  the  7th  triangle  number  would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
    first ten terms would be:

                    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

    Let us list the factors of the first seven triangle numbers:

                                 1: 1
                                 3: 1,3
                                 6: 1,2,3,6
                                10: 1,2,5,10
                                15: 1,3,5,15
                                21: 1,3,7,21
                                28: 1,2,4,7,14,28

    We  can see that 28 is the first triangle number to have over five divisors.
    What  is  the  value  of the first triangle number to have over five hundred
    divisors?

                                Answer: 76576500
"""

import sys

sys.path.append("../")
# pylint: disable=wrong-import-position,import-error
import python.project_euler.project_euler as pe


def highly_divisible_triangular(lower_bound):
    """Returns it the triangular number that has at least over lower bound divisors"""
    triangular_numbers = [1]
    add = 1

    while len(pe.all_divisors(triangular_numbers[-1])) < lower_bound:
        add += 1
        triangular_numbers.append(triangular_numbers[-1] + add)

    return triangular_numbers[-1]


print(highly_divisible_triangular(500))
