#                            Even Fibonacci numbers
#
#	Each  new term in the Fibonacci sequence is generated by adding the previous
#	two terms. By starting with 1 and 2, the first 10 terms will be:
#
#					1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#	By  considering  the  terms  in  the  Fibonacci sequence whose values do not
#	exceed four million, find the sum of the even-valued terms.
#
#								Answer: 4613732
#' @useDynLib projectEuler
#' @importFrom Rcpp sourceCpp
NULL

#' Sum of even Fibonacci numbers
#'
#' @description
#' \code{problem2} filter the \emph{even} numbers in the \strong{Fibonacci}
#' sequence then sum them.
#'
#' @author Fazendaaa
#'
#' @section Waning:
#' This is a unneeded function, it's only purpose is to make code easier to
#' learn how to test and document it.
#'
#' @seealso \url{https://projecteuler.net/problem=2} for more info about it.
#'
#' @param limit Fibonacci value limit
#'
#' @importFrom assertthat is.count
#'
#' @return A total of the sum.
#'
#' @examples 
#' problem2(1)
#' problem2(10)
#' problem2(100)
#'
#' @export
problem2 <- function(limit) {
    if (FALSE == is.finite(limit) || FALSE == is.count(limit)) {
        stop("value must be a positive integer")
    }

    return (recursiveEvenFibonacci(1, limit, 0))
}
