#                            Even Fibonacci numbers
#
#	Each  new term in the Fibonacci sequence is generated by adding the previous
#	two terms. By starting with 1 and 2, the first 10 terms will be:
#
#					1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#	By  considering  the  terms  in  the  Fibonacci sequence whose values do not
#	exceed four million, find the sum of the even-valued terms.
#
#								Answer: 4613732

#' Fibonnacci number
#'
#' Gives the Fibonnacci number of given position.
#'
#' @aliases Fibonnacci position
#' @param limit A positive integer.
#' @return a positive integer.
#' @examples
#' \dontrun{
#' fibonnacci(1)
#' fibonnacci(20)
#' }
#' @keywords internal
fibonnacci <- function(limit) {
    if (1 >= limit) {
        return (1);
    }

    return (fibonnacci(limit - 1) + fibonnacci(limit - 2))
}

#' Sum of even Fibonacci numbers
#'
#' Just filter the even numbers in the Fibonnacci sequence then sum it.
#'
#' @aliases even sum
#' @seealso \url{https://projecteuler.net/problem=2} for more info about it.
#' @inheritParams fibonnacci
#' @importFrom assertthat is.count
#' @return A total of the sum.
#' @examples 
#' problem2(1)
#' problem2(10)
#' @export
problem2 <- function(limit) {
    if (FALSE == is.finite(limit) || FALSE == is.count(limit)) {
        stop("value must be a positive integer")
    }

    total <- 0
    value <- 0
    position <- 0

    while (value <= limit) {
        position <- position + 1
        value <- fibonnacci(position)


        if (0 == value %% 2) {
            total <- total + value
        }
    }

    return (total)
}
