#                            Even Fibonacci numbers
#
#	Each  new term in the Fibonacci sequence is generated by adding the previous
#	two terms. By starting with 1 and 2, the first 10 terms will be:
#
#					1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#	By  considering  the  terms  in  the  Fibonacci sequence whose values do not
#	exceed four million, find the sum of the even-valued terms.
#
#								Answer: 4613732

#' Fibonnacci number
#'
#' \code{fibonnacci} gives the Fibonnacci number of given position.
#'
#' @keywords internal
#' @param limit A positive integer.
#' @return a positive integer.
#' @examples
#' fibonnacci(1) # 1
#' fibonnacci(2) # 2
#' fibonnacci(3) # 3
#' fibonnacci(4) # 5
fibonnacci <- function(limit) if (1 >= limit) 1 else fibonnacci(limit - 1) + fibonnacci(limit - 2)

#' Sum of even Fibonacci numbers
#'
#' @export
#' @seealso \url{https://projecteuler.net/problem=2} for more info about it.
#' @describeIn fibonnacci \code{problem2} just filter the even Fibonnacci sequence then sum it.
#' @inheritParams fibonnacci.
#' @importFrom assertthat is.count
#' @return The total of the even Fibonnacci numbers.
#' @examples 
#' problem2(1) # 1
#' problem2(10) # 10
#' problem2(40000000) # 4613732
#' \dontrun{
#'     problem2(1.2)
#'     problem2('a')
#'     problem2(c(...))
#'}
problem2 <- function(limit) {
    if (FALSE == is.finite(limit) || FALSE == is.count(limit)) {
        stop("value must be a positive integer")
    }

    total <- 0
    value <- 0
    position <- 0

    while (value <= limit) {
        position <- position + 1
        value <- fibonnacci(position)


        if (0 == value %% 2) {
            total <- total + value
        }
    }

    return (total)
}
