#                            Even Fibonacci numbers
#
#	Each  new term in the Fibonacci sequence is generated by adding the previous
#	two terms. By starting with 1 and 2, the first 10 terms will be:
#
#					1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#	By  considering  the  terms  in  the  Fibonacci sequence whose values do not
#	exceed four million, find the sum of the even-valued terms.
#
#								Answer: 4613732
#' @useDynLib projectEuler
#' @importFrom Rcpp sourceCpp
NULL

recursiveEvenFibonacci <- function(position, limit, total) {
    value <- fibonacci(position)
    #cat("\nPosition: ", position, "\tFibonacci: ", value, "\n")
    newTotal <- if (0 == value %% 2) total + value else total

    return (if (value <= limit) recursiveEvenFibonacci (position + 1, limit, newTotal) else (total))
}

#' Sum of even Fibonacci numbers
#'
#' Just filter the even numbers in the Fibonacci sequence then sum it.
#'
#' @seealso \url{https://projecteuler.net/problem=2} for more info about it.
#' @inheritParams fibonacci
#' @importFrom assertthat is.count
#' @return A total of the sum.
#' @examples 
#' problem2(1)
#' problem2(10)
#' @export
problem2 <- function(limit) {
    if (FALSE == is.finite(limit) || FALSE == is.count(limit)) {
        stop("value must be a positive integer")
    }

    return (recursiveEvenFibonacci(1, limit, 0))
}
