# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns the sum of all of the even Fibonacci number starting at given
#' postion to its limits, saving in the total 
#'
#' @param position The current position
#' @param limit The wanted position
#' @param total The accumulated value
recursiveEvenFibonacci <- function(position, limit, total) {
    .Call('_projectEuler_recursiveEvenFibonacci', PACKAGE = 'projectEuler', position, limit, total)
}

#' Max PalindromeWhether or not is a palindrome
#'
#' The  largest  palindrome  from  comparison  from  a  given  palindrome and a
#' sequence to be verified
#'
#' @param old Max palindrome so far
#' @param from Lower limit to check data
#' @param limit Upper limit to check data
#' @return The largest palindrome
#' @examples
#' \dontrun{
#' maxPalindrome(1, 2, 9)
#' maxPalindrome(29, 79, 99)
#' maxPalindrome(126, 345, 999)
#' }
maxPalindrome <- function(old, from, limit) {
    .Call('_projectEuler_maxPalindrome', PACKAGE = 'projectEuler', old, from, limit)
}

#' Multiply Range
#'
#' @description
#' \code{multiplyRange} finds the max number of digits multiplication given due
#' range
#'
#' @author Fazendaaa
#'
#' @param numbers Digits to iterate over
#' @param start Begin point
#' @param end Finish point
#'
#' @return The expected value
#'
#' @examples
#' problem8(c(1, 2, 3, 4, 5), -1, 2)
#' problem8((1:10), 0, 4)
#' problem8((1:100), 5, 13)
#'
NULL

#' Greatest
#'
#' @description
#' \code{greatest} finds the max number of digits multiplication
#'
#' @author Fazendaaa
#'
#' @param numbers Digits to iterate over
#' @param digits Max number of digits to compute
#'
#' @return The expected value
#'
#' @examples
#' problem8(c(1, 2, 3, 4, 5), 2)
#' problem8((1:10), 4)
#' problem8((1:100), 13)
#'
greatestProduct <- function(numbers, digits) {
    .Call('_projectEuler_greatestProduct', PACKAGE = 'projectEuler', numbers, digits)
}

#' Erastosthenes Sieve
#'
#' Calculates the all prime numbers up till given limit
#' 
#' @seeAlso \url{https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes} for more
#' info about how it works
#' @param limit Calculation limit
#' @return A list containing all prime numbers 
#' @examples
#' erastosthenesSieve(100)
#' erastosthenesSieve(200)
#' erastosthenesSieve(300)
erastosthenesSieve <- function(limit) {
    .Call('_projectEuler_erastosthenesSieve', PACKAGE = 'projectEuler', limit)
}

