# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Seeks a number in the Fibonacci sequence
#'
#' @param position The wanted position
fibonacci <- function(position) {
    .Call('_projectEuler_fibonacci', PACKAGE = 'projectEuler', position)
}

