# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Returns the sum of all of the even Fibonacci number starting at given
#' postion to its limits, saving in the total 
#'
#' @param position The current position
#' @param limit The wanted position
#' @param total The accumulated value
recursiveEvenFibonacci <- function(position, limit, total) {
    .Call('_projectEuler_recursiveEvenFibonacci', PACKAGE = 'projectEuler', position, limit, total)
}

